In [25]:
import pandas as pd

In [26]:
data = pd.read_csv("C:/Users/user/Downloads/bank.csv.zip")
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [27]:
data.drop(['default','contact','pdays','poutcome'],axis='columns',inplace=True)

In [28]:
inputs = data.drop('loan',axis='columns')
target = data['loan'].map({'yes':1,'no':0})

In [29]:
inputs

,age,job,marital,education,balance,housing,day,month,duration,campaign,previous,deposit
0,59,admin.,married,secondary,2343,yes,5,may,1042,1,0,yes
1,56,admin.,married,secondary,45,no,5,may,1467,1,0,yes
2,41,technician,married,secondary,1270,yes,5,may,1389,1,0,yes
3,55,services,married,secondary,2476,yes,5,may,579,1,0,yes
4,54,admin.,married,tertiary,184,no,5,may,673,2,0,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,1,yes,20,apr,257,1,0,no
11158,39,services,married,secondary,733,no,16,jun,83,4,0,no
11159,32,technician,single,secondary,29,no,19,aug,156,2,0,no
11160,43,technician,married,secondary,0,no,8,may,9,2,5,no
11161,34,technician,married,secondary,0,no,9,jul,628,1,0,no

In [30]:
target

0        0
1        0
2        0
3        0
4        0
        ..
11157    0
11158    0
11159    0
11160    1
11161    0
Name: loan, Length: 11162, dtype: int64

In [31]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [32]:
age_ = LabelEncoder()
job_ = LabelEncoder()
marital_= LabelEncoder()
education_= LabelEncoder()	
balance_= LabelEncoder()	
housing_= LabelEncoder()	
month_= LabelEncoder()		
deposit_= LabelEncoder()

In [33]:
inputs['age_'] = age_.fit_transform(inputs['age'])
inputs['job_'] = job_.fit_transform(inputs['job'])
inputs['marital_'] = marital_.fit_transform(inputs['marital'])
inputs['education_'] = education_.fit_transform(inputs['education'])
inputs['balance_'] = balance_.fit_transform(inputs['balance'])
inputs['housing_'] = housing_.fit_transform(inputs['housing'])
inputs['month_'] = month_.fit_transform(inputs['month'])
inputs['deposit_'] = deposit_.fit_transform(inputs['deposit'])

In [34]:
input_n = inputs.drop(['age','job','marital','education','balance','housing','month','deposit'],axis='columns')

In [35]:
x_train,x_test,y_train,y_test = train_test_split(input_n,target,test_size=0.2)

In [36]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [37]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [38]:
model.score(x_test,y_test)

0.780564263322884

In [39]:
x_test

,day,duration,campaign,previous,age_,job_,marital_,education_,balance_,housing_,month_,deposit_
6580,30,193,1,0,38,4,1,2,1162,0,0,0
8375,21,339,3,0,21,10,2,1,2447,1,8,0
7187,28,148,2,0,33,0,1,1,2456,0,4,0
9029,11,443,1,1,42,0,1,1,153,1,8,0
5609,17,38,1,0,18,0,1,1,1356,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2842,28,524,3,1,12,0,2,1,1318,1,10,1
10703,16,401,8,0,10,8,2,2,485,1,5,0
2500,12,306,1,3,37,4,1,0,537,0,1,1
10827,29,247,2,0,37,4,1,2,3713,0,10,0
3727,15,390,2,5,45,1,1,1,604,0,5,1

In [40]:
y_test

6580     0
8375     0
7187     0
9029     0
5609     0
        ..
2842     0
10703    0
2500     0
10827    0
3727     0
Name: loan, Length: 2233, dtype: int64

Let us now evaluate how accurately the model predicts whether an individual, based on specific categories, has taken a loan or not

In [41]:
#First person in the test data set: expected output - 0
model.predict([[30,219,5,0,11,1,1,0,1053,1,5,0]])

C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [42]:
#In order to remove warning, we are using indexing
#First person in the test data set: expected output - 0
model.predict(x_test.iloc[[0]])

array([0])

In [43]:
#Second person in the test data set: expected output - 1
model.predict(x_test.iloc[[1]])

array([0])

This output does not align with our expectations, as there may be instances where the model’s predictions are incorrect

In [44]:
#Third person in the test data set: expected output - 0
model.predict(x_test.iloc[[3]])

array([1])

In [45]:
#Fourth person in the test data set: expected output - 0
model.predict(x_test.iloc[[4]])

array([0])

In [46]:
#Fifth person in the test data set: expected output - 0
model.predict(x_test.iloc[[5]])

array([0])

Hence, we observe that the model’s predictions were accurate in most cases, although there were a few exceptions.